workflows:
  ios-testflight:
    name: iOS TestFlight Beta
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: 3.38.1
      xcode: latest
      cocoapods: default
      groups:
        - firebase_credentials
      vars:
        BUNDLE_ID: "com.greengochat.greengochatapp"
        APP_STORE_APPLE_ID: "tommasi.mauro@icloud.com"
    scripts:
      - name: Install Firebase config files
        script: |
          #!/bin/sh
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo $FIREBASE_OPTIONS_DART | base64 --decode > $CM_BUILD_DIR/lib/firebase_options.dart
      - name: Create Secrets.xcconfig
        script: |
          echo "// Secrets" > "$CM_BUILD_DIR/ios/Flutter/Secrets.xcconfig"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Run build_runner
        script: |
          dart run build_runner build --delete-conflicting-outputs
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Set up code signing
        script: |
          keychain initialize
          echo "CERTIFICATE_PRIVATE_KEY is set: $([ -n "$CERTIFICATE_PRIVATE_KEY" ] && echo YES || echo NO)"
          app-store-connect fetch-signing-files "com.greengochat.greengochatapp" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key="$CERTIFICATE_PRIVATE_KEY"
          keychain add-certificates
          xcode-project use-profiles
      - name: Debug signing setup
        script: |
          echo "=== Checking export_options.plist ==="
          cat $HOME/export_options.plist || echo "NOT FOUND at HOME"
          cat /Users/builder/export_options.plist || echo "NOT FOUND at /Users/builder"
          echo "=== Checking CODE_SIGN_STYLE in project ==="
          grep "CODE_SIGN_STYLE" $CM_BUILD_DIR/ios/Runner.xcodeproj/project.pbxproj
          echo "=== Checking PROVISIONING_PROFILE in project ==="
          grep "PROVISIONING_PROFILE" $CM_BUILD_DIR/ios/Runner.xcodeproj/project.pbxproj || echo "No PROVISIONING_PROFILE found"
          echo "=== Installed provisioning profiles ==="
          ls ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles directory"
      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --build-name=1.0.13 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
      email:
        recipients:
          - tommasi.mauro@icloud.com
        notify:
          success: true
          failure: true

  android-release:
    name: Android APK Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.1
      groups:
        - firebase_credentials
      vars:
        BUNDLE_ID: "com.greengochat.greengochatapp"
    scripts:
      - name: Install Firebase config files
        script: |
          #!/bin/sh
          echo $GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo $FIREBASE_OPTIONS_DART | base64 --decode > $CM_BUILD_DIR/lib/firebase_options.dart
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Run build_runner
        script: |
          dart run build_runner build --delete-conflicting-outputs
      - name: Build APK and AAB
        script: |
          flutter build apk --release
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - tommasi.mauro@icloud.com
        notify:
          success: true
          failure: true
