import 'package:equatable/equatable.dart';

/// Represents a cultural icebreaker suggestion
class Icebreaker extends Equatable {
  final String id;
  final String phrase;
  final String translation;
  final String languageCode;
  final String languageName;
  final String? pronunciation;
  final String? audioUrl;
  final String countryCode;
  final String countryName;
  final String culturalContext;
  final IcebreakerType type;
  final int xpReward;
  final bool isUsed;
  final DateTime? usedAt;

  const Icebreaker({
    required this.id,
    required this.phrase,
    required this.translation,
    required this.languageCode,
    required this.languageName,
    this.pronunciation,
    this.audioUrl,
    required this.countryCode,
    required this.countryName,
    required this.culturalContext,
    required this.type,
    this.xpReward = 15,
    this.isUsed = false,
    this.usedAt,
  });

  Icebreaker copyWith({
    String? id,
    String? phrase,
    String? translation,
    String? languageCode,
    String? languageName,
    String? pronunciation,
    String? audioUrl,
    String? countryCode,
    String? countryName,
    String? culturalContext,
    IcebreakerType? type,
    int? xpReward,
    bool? isUsed,
    DateTime? usedAt,
  }) {
    return Icebreaker(
      id: id ?? this.id,
      phrase: phrase ?? this.phrase,
      translation: translation ?? this.translation,
      languageCode: languageCode ?? this.languageCode,
      languageName: languageName ?? this.languageName,
      pronunciation: pronunciation ?? this.pronunciation,
      audioUrl: audioUrl ?? this.audioUrl,
      countryCode: countryCode ?? this.countryCode,
      countryName: countryName ?? this.countryName,
      culturalContext: culturalContext ?? this.culturalContext,
      type: type ?? this.type,
      xpReward: xpReward ?? this.xpReward,
      isUsed: isUsed ?? this.isUsed,
      usedAt: usedAt ?? this.usedAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        phrase,
        translation,
        languageCode,
        languageName,
        pronunciation,
        audioUrl,
        countryCode,
        countryName,
        culturalContext,
        type,
        xpReward,
        isUsed,
        usedAt,
      ];

  /// Pre-defined icebreakers for various countries
  static List<Icebreaker> getIcebreakersForCountry(String countryCode) {
    return _allIcebreakers
        .where((ib) => ib.countryCode.toLowerCase() == countryCode.toLowerCase())
        .toList();
  }

  static const List<Icebreaker> _allIcebreakers = [
    // Spanish (Spain)
    Icebreaker(
      id: 'es_greeting_1',
      phrase: '¡Hola! ¿Qué tal?',
      translation: 'Hello! How are you?',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'OH-lah keh TAHL',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'Casual greeting, shows friendliness',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'es_compliment_1',
      phrase: 'Tienes una sonrisa muy bonita',
      translation: 'You have a very beautiful smile',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'tee-EH-nehs OO-nah sohn-REE-sah mwee boh-NEE-tah',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'A sincere compliment that\'s well-received in Spanish culture',
      type: IcebreakerType.compliment,
    ),

    // French (France)
    Icebreaker(
      id: 'fr_greeting_1',
      phrase: 'Salut! Comment ça va?',
      translation: 'Hi! How\'s it going?',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'sah-LOO koh-mohn sah VAH',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'Informal greeting, good for casual conversations',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'fr_interest_1',
      phrase: 'Tu aimes voyager?',
      translation: 'Do you like to travel?',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'too ehm vwah-yah-ZHAY',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'French people love discussing travel experiences',
      type: IcebreakerType.interest,
    ),

    // Spanish — expanded
    Icebreaker(
      id: 'es_interest_1',
      phrase: '¿Te gusta bailar?',
      translation: 'Do you like to dance?',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'teh GOOS-tah bye-LAHR',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'Dancing is a big part of Spanish nightlife and culture',
      type: IcebreakerType.interest,
    ),
    Icebreaker(
      id: 'es_question_1',
      phrase: '¿Cuál es tu lugar favorito en el mundo?',
      translation: 'What is your favorite place in the world?',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'kwahl ehs too loo-GAHR fah-voh-REE-toh ehn ehl MOON-doh',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'Spaniards love travel and sharing stories about places',
      type: IcebreakerType.question,
    ),
    Icebreaker(
      id: 'es_cultural_1',
      phrase: '¿Has probado la paella de verdad?',
      translation: 'Have you tried real paella?',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'ahs proh-BAH-doh lah pah-EH-yah deh vehr-DAHD',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'Food is central to Spanish culture, paella is a point of pride',
      type: IcebreakerType.cultural,
    ),
    Icebreaker(
      id: 'es_compliment_2',
      phrase: 'Me encanta tu energía',
      translation: 'I love your energy',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'meh ehn-KAHN-tah too eh-nehr-HEE-ah',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'A warm compliment that goes beyond appearance',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'es_greeting_2',
      phrase: '¡Buenas! ¿Cómo va todo?',
      translation: 'Hey! How\'s everything going?',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'BWEH-nahs KOH-moh vah TOH-doh',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'Friendly informal greeting commonly used in Spain',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'es_interest_2',
      phrase: '¿Qué serie estás viendo?',
      translation: 'What show are you watching?',
      languageCode: 'es',
      languageName: 'Spanish',
      pronunciation: 'keh SEH-ryeh ehs-TAHS VYEHN-doh',
      countryCode: 'ES',
      countryName: 'Spain',
      culturalContext: 'Great modern conversation starter, shows are widely discussed',
      type: IcebreakerType.interest,
    ),

    // French — expanded
    Icebreaker(
      id: 'fr_compliment_1',
      phrase: 'Tu as un sourire magnifique',
      translation: 'You have a magnificent smile',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'too ah uhn soo-REER mah-nyee-FEEK',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'French romance appreciates poetic compliments',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'fr_question_1',
      phrase: 'Quel est ton endroit préféré à Paris?',
      translation: 'What is your favorite place in Paris?',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'kehl eh tohn ahn-DRWAH preh-feh-RAY ah pah-REE',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'Paris is a source of pride, great for showing interest',
      type: IcebreakerType.question,
    ),
    Icebreaker(
      id: 'fr_cultural_1',
      phrase: 'Tu préfères le vin rouge ou blanc?',
      translation: 'Do you prefer red or white wine?',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'too preh-FEHR luh vehn roozh oo blahn',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'Wine culture is integral to French social life',
      type: IcebreakerType.cultural,
    ),
    Icebreaker(
      id: 'fr_compliment_2',
      phrase: 'Tu as beaucoup de charme',
      translation: 'You have a lot of charm',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'too ah boh-KOO duh SHAHRM',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'A sophisticated compliment valued in French dating culture',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'fr_greeting_2',
      phrase: 'Coucou! Ça fait plaisir de te voir',
      translation: 'Hey! It\'s nice to see you',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'koo-KOO sah feh pleh-ZEER duh tuh VWAHR',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'Coucou is a playful, affectionate way to say hello',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'fr_interest_2',
      phrase: 'Tu aimes la cuisine française?',
      translation: 'Do you like French cuisine?',
      languageCode: 'fr',
      languageName: 'French',
      pronunciation: 'too ehm lah kwee-ZEEN frahn-SEHZ',
      countryCode: 'FR',
      countryName: 'France',
      culturalContext: 'Food is a serious topic and great way to connect in France',
      type: IcebreakerType.interest,
    ),

    // German (Germany)
    Icebreaker(
      id: 'de_greeting_1',
      phrase: 'Hallo! Wie geht\'s?',
      translation: 'Hello! How are you?',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'HAH-loh vee GAYTS',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Casual greeting, Germans appreciate directness',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'de_interest_1',
      phrase: 'Was machst du gerne in deiner Freizeit?',
      translation: 'What do you like to do in your free time?',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'vahs MAHKHST doo GEHR-neh in DYE-nehr FRY-tsyt',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Germans value meaningful conversations about interests',
      type: IcebreakerType.interest,
    ),

    // Italian (Italy)
    Icebreaker(
      id: 'it_greeting_1',
      phrase: 'Ciao! Come stai?',
      translation: 'Hi! How are you?',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'CHOW KOH-meh STYE',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Warm, friendly greeting typical of Italian culture',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'it_compliment_1',
      phrase: 'Hai degli occhi bellissimi',
      translation: 'You have beautiful eyes',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'eye DEH-lyee OH-kee beh-LEE-see-mee',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Italians are expressive and appreciate romantic compliments',
      type: IcebreakerType.compliment,
    ),

    // Portuguese (Brazil)
    Icebreaker(
      id: 'pt_greeting_1',
      phrase: 'Oi! Tudo bem?',
      translation: 'Hi! Everything good?',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'oy TOO-doo beng',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Brazilians are warm and friendly, this is a casual greeting',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'pt_interest_1',
      phrase: 'Você gosta de música?',
      translation: 'Do you like music?',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'voh-SEH GOHSH-tah jee MOO-zee-kah',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Music is central to Brazilian culture, great conversation starter',
      type: IcebreakerType.interest,
    ),

    // German — expanded
    Icebreaker(
      id: 'de_compliment_1',
      phrase: 'Du hast ein tolles Lachen',
      translation: 'You have a great laugh',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'doo hahst ayn TOL-es LAH-khen',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Genuine compliments are valued over flattery in Germany',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'de_question_1',
      phrase: 'Warst du schon mal in den Alpen?',
      translation: 'Have you ever been to the Alps?',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'vahrst doo shohn mahl in dehn AHL-pen',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Nature and outdoors are important in German culture',
      type: IcebreakerType.question,
    ),
    Icebreaker(
      id: 'de_cultural_1',
      phrase: 'Magst du Bier oder Wein lieber?',
      translation: 'Do you prefer beer or wine?',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'mahgst doo beer OH-der vyn LEE-ber',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Beer culture is central to German socializing',
      type: IcebreakerType.cultural,
    ),
    Icebreaker(
      id: 'de_greeting_2',
      phrase: 'Na, alles klar bei dir?',
      translation: 'Hey, everything good with you?',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'nah AH-les klahr by deer',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Casual friendly greeting, shows you care',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'de_interest_2',
      phrase: 'Welche Musik hörst du am liebsten?',
      translation: 'What music do you like most?',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'VEHL-kheh moo-ZEEK hurst doo ahm LEEB-sten',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Music is a universal topic in German conversations',
      type: IcebreakerType.interest,
    ),
    Icebreaker(
      id: 'de_compliment_2',
      phrase: 'Du bist echt sympathisch',
      translation: 'You are really likeable',
      languageCode: 'de',
      languageName: 'German',
      pronunciation: 'doo bist ekht zoom-PAH-tish',
      countryCode: 'DE',
      countryName: 'Germany',
      culturalContext: 'Sympathisch is one of the highest personality compliments',
      type: IcebreakerType.compliment,
    ),

    // Italian — expanded
    Icebreaker(
      id: 'it_interest_1',
      phrase: 'Ti piace la cucina italiana?',
      translation: 'Do you like Italian cuisine?',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'tee PYAH-cheh lah koo-CHEE-nah ee-tah-LYAH-nah',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Food is the heart of Italian culture and connection',
      type: IcebreakerType.interest,
    ),
    Icebreaker(
      id: 'it_question_1',
      phrase: 'Qual è il tuo piatto preferito?',
      translation: 'What is your favorite dish?',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'kwahl eh eel TOO-oh PYAHT-toh preh-feh-REE-toh',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Italians are passionate about food — great conversation',
      type: IcebreakerType.question,
    ),
    Icebreaker(
      id: 'it_cultural_1',
      phrase: 'Caffè o aperitivo?',
      translation: 'Coffee or aperitivo?',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'kahf-FEH oh ah-peh-ree-TEE-voh',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'The aperitivo tradition is a beloved Italian social ritual',
      type: IcebreakerType.cultural,
    ),
    Icebreaker(
      id: 'it_greeting_2',
      phrase: 'Ehi, bello/a! Tutto bene?',
      translation: 'Hey, beautiful! Everything good?',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'eh-EE BEHL-loh/ah TOOT-toh BEH-neh',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Warm and affectionate greeting, typical Italian warmth',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'it_compliment_2',
      phrase: 'Sei davvero simpatico/a',
      translation: 'You\'re really nice/likeable',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'say dahv-VEH-roh seem-PAH-tee-koh/ah',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Simpatico is a high personality compliment in Italian',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'it_interest_2',
      phrase: 'Ti piace viaggiare?',
      translation: 'Do you like to travel?',
      languageCode: 'it',
      languageName: 'Italian',
      pronunciation: 'tee PYAH-cheh vyahd-JAH-reh',
      countryCode: 'IT',
      countryName: 'Italy',
      culturalContext: 'Italians love discussing travel, culture and experiences',
      type: IcebreakerType.interest,
    ),

    // Portuguese (Brazil) — expanded
    Icebreaker(
      id: 'pt_compliment_1',
      phrase: 'Você tem um sorriso lindo',
      translation: 'You have a beautiful smile',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'voh-SEH tehng oom soh-HEE-zoo LEEN-doo',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Brazilians are warm and appreciate sincere compliments',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'pt_question_1',
      phrase: 'Você já foi para a praia hoje?',
      translation: 'Have you been to the beach today?',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'voh-SEH zhah foy PAH-rah ah PRY-ah OH-zhee',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Beach culture is huge in Brazil',
      type: IcebreakerType.question,
    ),
    Icebreaker(
      id: 'pt_cultural_1',
      phrase: 'Samba ou forró?',
      translation: 'Samba or forró?',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'SAHM-bah oh foh-HOH',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Music and dance are at the heart of Brazilian identity',
      type: IcebreakerType.cultural,
    ),
    Icebreaker(
      id: 'pt_greeting_2',
      phrase: 'E aí, beleza?',
      translation: 'What\'s up, all good?',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'ee ah-EE beh-LEH-zah',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Very casual Brazilian slang greeting',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'pt_compliment_2',
      phrase: 'Você é muito gente boa',
      translation: 'You\'re really cool/a great person',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'voh-SEH eh MOO-ee-too ZHEHN-chee BOH-ah',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Gente boa means good people — a high compliment in Brazil',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'pt_interest_2',
      phrase: 'Você curte carnaval?',
      translation: 'Do you enjoy carnival?',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      pronunciation: 'voh-SEH KOOR-chee kahr-nah-VAHL',
      countryCode: 'BR',
      countryName: 'Brazil',
      culturalContext: 'Carnival is Brazil\'s biggest celebration',
      type: IcebreakerType.interest,
    ),

    // English — 8 icebreakers
    Icebreaker(
      id: 'en_greeting_1',
      phrase: 'Hey! How\'s your day going?',
      translation: 'Hey! How\'s your day going?',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'hey howz yor day GOH-ing',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'Casual and friendly American greeting',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'en_compliment_1',
      phrase: 'You have an amazing smile',
      translation: 'You have an amazing smile',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'yoo hav an ah-MAY-zing smyl',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'A genuine compliment that works universally',
      type: IcebreakerType.compliment,
    ),
    Icebreaker(
      id: 'en_interest_1',
      phrase: 'What\'s the best trip you\'ve ever taken?',
      translation: 'What\'s the best trip you\'ve ever taken?',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'wots thee best trip yoov EH-ver TAY-ken',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'Travel stories create deep connections',
      type: IcebreakerType.interest,
    ),
    Icebreaker(
      id: 'en_question_1',
      phrase: 'What are you passionate about?',
      translation: 'What are you passionate about?',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'wot ar yoo PASH-un-it ah-BOWT',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'Shows genuine interest beyond surface level',
      type: IcebreakerType.question,
    ),
    Icebreaker(
      id: 'en_cultural_1',
      phrase: 'Have you seen any good movies lately?',
      translation: 'Have you seen any good movies lately?',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'hav yoo seen EN-ee good MOO-veez LAYT-lee',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'Pop culture is a universal conversation starter',
      type: IcebreakerType.cultural,
    ),
    Icebreaker(
      id: 'en_greeting_2',
      phrase: 'Hi there! I love your vibe',
      translation: 'Hi there! I love your vibe',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'hai thehr ai luv yor vyb',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'Modern, casual compliment-greeting combo',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'en_interest_2',
      phrase: 'Do you have any fun plans for the weekend?',
      translation: 'Do you have any fun plans for the weekend?',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'doo yoo hav EN-ee fun planz for thee WEEK-end',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'Opens the door to making plans together naturally',
      type: IcebreakerType.interest,
    ),
    Icebreaker(
      id: 'en_compliment_2',
      phrase: 'Your energy is contagious',
      translation: 'Your energy is contagious',
      languageCode: 'en',
      languageName: 'English',
      pronunciation: 'yor EN-er-jee iz kon-TAY-jus',
      countryCode: 'US',
      countryName: 'United States',
      culturalContext: 'A personality compliment that feels genuine and warm',
      type: IcebreakerType.compliment,
    ),

    // Portuguese (Portugal)
    Icebreaker(
      id: 'pt_pt_greeting_1',
      phrase: 'Olá! Como estás?',
      translation: 'Hello! How are you?',
      languageCode: 'pt',
      languageName: 'Portuguese',
      pronunciation: 'oh-LAH KOH-moo ehs-TAHSH',
      countryCode: 'PT',
      countryName: 'Portugal',
      culturalContext: 'Standard Portuguese greeting',
      type: IcebreakerType.greeting,
    ),
    Icebreaker(
      id: 'pt_pt_compliment_1',
      phrase: 'Tens um sorriso lindo',
      translation: 'You have a beautiful smile',
      languageCode: 'pt',
      languageName: 'Portuguese',
      pronunciation: 'tenz oom soh-HEE-zoo LEEN-doo',
      countryCode: 'PT',
      countryName: 'Portugal',
      culturalContext: 'Portuguese people appreciate heartfelt compliments',
      type: IcebreakerType.compliment,
    ),
  ];
}

enum IcebreakerType {
  greeting,
  compliment,
  interest,
  question,
  cultural,
}

extension IcebreakerTypeExtension on IcebreakerType {
  String get displayName {
    switch (this) {
      case IcebreakerType.greeting:
        return 'Greeting';
      case IcebreakerType.compliment:
        return 'Compliment';
      case IcebreakerType.interest:
        return 'Interest Question';
      case IcebreakerType.question:
        return 'Question';
      case IcebreakerType.cultural:
        return 'Cultural';
    }
  }

  String get icon {
    switch (this) {
      case IcebreakerType.greeting:
        return '👋';
      case IcebreakerType.compliment:
        return '💫';
      case IcebreakerType.interest:
        return '❓';
      case IcebreakerType.question:
        return '💭';
      case IcebreakerType.cultural:
        return '🌍';
    }
  }
}
