import 'package:equatable/equatable.dart';
import 'language_phrase.dart';

/// Represents a purchasable language pack
class LanguagePack extends Equatable {
  final String id;
  final String name;
  final String description;
  final String languageCode;
  final String languageName;
  final PhraseCategory category;
  final int phraseCount;
  final int coinPrice;
  final bool isPurchased;
  final DateTime? purchasedAt;
  final String iconEmoji;
  final List<String> previewPhrases;
  final PackTier tier;

  const LanguagePack({
    required this.id,
    required this.name,
    required this.description,
    required this.languageCode,
    required this.languageName,
    required this.category,
    required this.phraseCount,
    required this.coinPrice,
    this.isPurchased = false,
    this.purchasedAt,
    required this.iconEmoji,
    this.previewPhrases = const [],
    this.tier = PackTier.standard,
  });

  LanguagePack copyWith({
    String? id,
    String? name,
    String? description,
    String? languageCode,
    String? languageName,
    PhraseCategory? category,
    int? phraseCount,
    int? coinPrice,
    bool? isPurchased,
    DateTime? purchasedAt,
    String? iconEmoji,
    List<String>? previewPhrases,
    PackTier? tier,
  }) {
    return LanguagePack(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      languageCode: languageCode ?? this.languageCode,
      languageName: languageName ?? this.languageName,
      category: category ?? this.category,
      phraseCount: phraseCount ?? this.phraseCount,
      coinPrice: coinPrice ?? this.coinPrice,
      isPurchased: isPurchased ?? this.isPurchased,
      purchasedAt: purchasedAt ?? this.purchasedAt,
      iconEmoji: iconEmoji ?? this.iconEmoji,
      previewPhrases: previewPhrases ?? this.previewPhrases,
      tier: tier ?? this.tier,
    );
  }

  @override
  List<Object?> get props => [
        id,
        name,
        description,
        languageCode,
        languageName,
        category,
        phraseCount,
        coinPrice,
        isPurchased,
        purchasedAt,
        iconEmoji,
        previewPhrases,
        tier,
      ];

  /// Pre-defined language packs available in the shop
  static List<LanguagePack> get availablePacks => [
    // ═══════════════════════════════════════════════════════════════
    // ROMANTIC PHRASES — 7 packs (50 phrases, 100 coins, standard)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'romantic_spanish',
      name: 'Romantic Spanish',
      description: 'Express your deepest feelings in the language of passion',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['Te quiero mucho', 'Eres el amor de mi vida', 'Mi coraz\u00f3n es tuyo'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'romantic_french',
      name: 'Romantic French',
      description: 'Whisper sweet nothings in the language of love',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['Je t\'aime de tout mon coeur', 'Tu es l\'amour de ma vie', 'Mon coeur est \u00e0 toi'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'romantic_italian',
      name: 'Romantic Italian',
      description: 'Speak amore like a true Italian romantic',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['Ti amo con tutto il cuore', 'Sei la mia anima gemella', 'Non posso vivere senza di te'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'romantic_german',
      name: 'Romantic German',
      description: 'Discover the tender side of the German language',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['Ich liebe dich', 'Du bist die Liebe meines Lebens', 'Mein Herz geh\u00f6rt dir'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'romantic_english',
      name: 'Romantic English',
      description: 'Classic and heartfelt English love phrases',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['You mean the world to me', 'I fall for you more every day', 'You are my everything'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'romantic_portuguese',
      name: 'Romantic Portuguese',
      description: 'Poetic romance in European Portuguese',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['Amo-te com todo o meu cora\u00e7\u00e3o', '\u00c9s o amor da minha vida', 'O meu cora\u00e7\u00e3o \u00e9 teu'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'romantic_brazilian',
      name: 'Romantic Brazilian Portuguese',
      description: 'Passionate expressions the Brazilian way',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.romantic,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '❤️',
      previewPhrases: ['Eu te amo demais', 'Voc\u00ea \u00e9 o amor da minha vida', 'Meu cora\u00e7\u00e3o \u00e9 seu'],
      tier: PackTier.standard,
    ),

    // ═══════════════════════════════════════════════════════════════
    // FLIRTY PHRASES — 7 packs (45 phrases, 120 coins, standard)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'flirty_spanish',
      name: 'Flirty Spanish',
      description: 'Playful and cheeky phrases to spark romance',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['\u00bfTienes un mapa? Me perd\u00ed en tus ojos', 'Me encantas', 'No puedo dejar de pensar en ti'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'flirty_french',
      name: 'Flirty French',
      description: 'Charm and seduce with effortless French flair',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['Tu as de beaux yeux', 'Je pense \u00e0 toi tout le temps', 'Tu me fais craquer'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'flirty_italian',
      name: 'Flirty Italian',
      description: 'Turn on the Italian charm with smooth phrases',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['Hai degli occhi bellissimi', 'Mi fai battere il cuore', 'Sei irresistibile'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'flirty_german',
      name: 'Flirty German',
      description: 'Flirtatious German phrases to break the ice',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['Du hast wundersch\u00f6ne Augen', 'Ich kann nicht aufh\u00f6ren an dich zu denken', 'Du bist echt s\u00fc\u00df'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'flirty_english',
      name: 'Flirty English',
      description: 'Smooth English pickup lines and flirty banter',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['Are you a magician? Because you just made my day', 'I can\'t stop thinking about you', 'You\'ve got a gorgeous smile'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'flirty_portuguese',
      name: 'Flirty Portuguese',
      description: 'Charming European Portuguese flirtation',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['Tens uns olhos lindos', 'N\u00e3o consigo parar de pensar em ti', '\u00c9s muito giro/gira'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'flirty_brazilian',
      name: 'Flirty Brazilian Portuguese',
      description: 'Fun and bold Brazilian flirting style',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.flirty,
      phraseCount: 45,
      coinPrice: 120,
      iconEmoji: '😏',
      previewPhrases: ['Voc\u00ea \u00e9 muito lindo/linda', 'N\u00e3o consigo parar de pensar em voc\u00ea', 'Voc\u00ea \u00e9 demais'],
      tier: PackTier.standard,
    ),

    // ═══════════════════════════════════════════════════════════════
    // TRAVEL & CULTURE — 7 packs (60 phrases, 200 coins, premium)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'travel_spanish',
      name: 'Spanish Explorer',
      description: 'Navigate Spain and Latin America with ease',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['\u00bfD\u00f3nde est\u00e1 la estaci\u00f3n?', 'Me gustar\u00eda una habitaci\u00f3n', '\u00bfCu\u00e1nto cuesta?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'travel_french',
      name: 'French Explorer',
      description: 'Explore Paris, the Riviera, and beyond',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['O\u00f9 se trouve la gare?', 'Je voudrais une chambre', 'Combien \u00e7a co\u00fbte?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'travel_italian',
      name: 'Italian Explorer',
      description: 'Discover Italy from Rome to the Amalfi Coast',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['Dov\'\u00e8 la stazione?', 'Vorrei una camera', 'Quanto costa?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'travel_german',
      name: 'German Explorer',
      description: 'Navigate Germany, Austria, and Switzerland',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['Wo ist der Bahnhof?', 'Ich h\u00e4tte gern ein Zimmer', 'Was kostet das?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'travel_english',
      name: 'English Explorer',
      description: 'Essential travel English for any destination',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['Where is the train station?', 'I would like to book a room', 'How much does this cost?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'travel_portuguese',
      name: 'Portuguese Explorer',
      description: 'Explore Portugal from Lisbon to the Algarve',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['Onde fica a esta\u00e7\u00e3o?', 'Queria um quarto', 'Quanto custa?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'travel_brazilian',
      name: 'Brazilian Explorer',
      description: 'Experience Brazil from Rio to the Amazon',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.travelCulture,
      phraseCount: 60,
      coinPrice: 200,
      iconEmoji: '✈️',
      previewPhrases: ['Onde fica a esta\u00e7\u00e3o?', 'Eu gostaria de um quarto', 'Quanto custa isso?'],
      tier: PackTier.premium,
    ),

    // ═══════════════════════════════════════════════════════════════
    // BUSINESS — 7 packs (55 phrases, 150 coins, premium)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'business_spanish',
      name: 'Business Spanish',
      description: 'Professional phrases for the Spanish-speaking world',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Encantado de conocerle', 'Gracias por su oferta', '\u00bfCu\u00e1ndo podemos reunirnos?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'business_french',
      name: 'Business French',
      description: 'Professional etiquette and formal French',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Enchant\u00e9 de vous rencontrer', 'Merci pour votre proposition', 'Quand pouvons-nous nous r\u00e9unir?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'business_italian',
      name: 'Business Italian',
      description: 'Navigate Italian business culture with confidence',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Piacere di conoscerla', 'Grazie per la sua offerta', 'Quando possiamo incontrarci?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'business_german',
      name: 'Business German',
      description: 'Formal German for meetings and negotiations',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Guten Tag, ich bin...', 'Vielen Dank f\u00fcr Ihr Angebot', 'Wann k\u00f6nnen wir uns treffen?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'business_english',
      name: 'Business English',
      description: 'Professional English for global communication',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Pleased to meet you', 'Thank you for your proposal', 'When can we schedule a meeting?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'business_portuguese',
      name: 'Business Portuguese',
      description: 'Formal Portuguese for professional settings',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Prazer em conhec\u00ea-lo', 'Obrigado pela sua proposta', 'Quando podemos reunir-nos?'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'business_brazilian',
      name: 'Business Brazilian Portuguese',
      description: 'Professional phrases for the Brazilian market',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.business,
      phraseCount: 55,
      coinPrice: 150,
      iconEmoji: '💼',
      previewPhrases: ['Prazer em conhec\u00ea-lo', 'Obrigado pela sua proposta', 'Quando podemos nos reunir?'],
      tier: PackTier.premium,
    ),

    // ═══════════════════════════════════════════════════════════════
    // EMERGENCY — 7 packs (40 phrases, 100 coins, standard)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'emergency_spanish',
      name: 'Emergency Spanish',
      description: 'Critical phrases for urgent situations in Spanish',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['\u00a1Ayuda!', 'Necesito un m\u00e9dico', 'Llame a la polic\u00eda'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'emergency_french',
      name: 'Emergency French',
      description: 'Essential French for emergencies and safety',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['Au secours!', 'J\'ai besoin d\'un m\u00e9decin', 'Appelez la police'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'emergency_italian',
      name: 'Emergency Italian',
      description: 'Stay safe with essential Italian emergency phrases',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['Aiuto!', 'Ho bisogno di un medico', 'Chiamate la polizia'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'emergency_german',
      name: 'Emergency German',
      description: 'Crucial German phrases when you need help fast',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['Hilfe!', 'Ich brauche einen Arzt', 'Rufen Sie die Polizei'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'emergency_english',
      name: 'Emergency English',
      description: 'Life-saving English phrases for any emergency',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['Help!', 'I need a doctor', 'Call the police'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'emergency_portuguese',
      name: 'Emergency Portuguese',
      description: 'Essential Portuguese for urgent situations',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['Socorro!', 'Preciso de um m\u00e9dico', 'Chame a pol\u00edcia'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'emergency_brazilian',
      name: 'Emergency Brazilian Portuguese',
      description: 'Critical phrases for emergencies in Brazil',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.emergency,
      phraseCount: 40,
      coinPrice: 100,
      iconEmoji: '🚨',
      previewPhrases: ['Socorro!', 'Preciso de um m\u00e9dico', 'Chame a pol\u00edcia, por favor'],
      tier: PackTier.standard,
    ),

    // ═══════════════════════════════════════════════════════════════
    // FOOD & DINING — 7 packs (50 phrases, 100 coins, standard)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'food_spanish',
      name: 'Spanish Food & Dining',
      description: 'Order tapas, wine, and more like a local',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['\u00a1Buen provecho!', 'La cuenta, por favor', 'Quisiera pedir...'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'food_french',
      name: 'French Food & Dining',
      description: 'Dine at Parisian bistros with perfect phrases',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['Bon app\u00e9tit!', 'L\'addition, s\'il vous pla\u00eet', 'Je voudrais commander...'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'food_italian',
      name: 'Italian Food & Dining',
      description: 'From pizza to fine dining, eat Italian style',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['Buon appetito!', 'Il conto, per favore', 'Vorrei ordinare...'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'food_german',
      name: 'German Food & Dining',
      description: 'Order Bratwurst, Bier, and more with confidence',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['Guten Appetit!', 'Die Rechnung, bitte', 'Ich m\u00f6chte bestellen...'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'food_english',
      name: 'English Food & Dining',
      description: 'Master restaurant etiquette and food vocabulary',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['Enjoy your meal!', 'Could I have the bill, please?', 'I would like to order...'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'food_portuguese',
      name: 'Portuguese Food & Dining',
      description: 'Savor Portuguese cuisine with the right words',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['Bom apetite!', 'A conta, por favor', 'Queria pedir...'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'food_brazilian',
      name: 'Brazilian Food & Dining',
      description: 'From churrasco to a\u00e7a\u00ed, eat like a Brazilian',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.foodDining,
      phraseCount: 50,
      coinPrice: 100,
      iconEmoji: '🍽️',
      previewPhrases: ['Bom apetite!', 'A conta, por favor', 'Eu gostaria de pedir...'],
      tier: PackTier.standard,
    ),

    // ═══════════════════════════════════════════════════════════════
    // IDIOMS & SLANG — 7 packs (40 phrases, 120 coins, standard)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'idioms_spanish',
      name: 'Spanish Idioms & Slang',
      description: 'Master colorful Spanish expressions and street talk',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['Estar en las nubes', 'Tirar la casa por la ventana', 'No hay moros en la costa'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'idioms_french',
      name: 'French Idioms & Slang',
      description: 'Speak like a true Parisian with classic expressions',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['Avoir le cafard', 'Poser un lapin', 'Ce n\'est pas la mer \u00e0 boire'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'idioms_italian',
      name: 'Italian Idioms & Slang',
      description: 'Sound like a native with Italian proverbs and slang',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['In bocca al lupo', 'Acqua in bocca', 'Non tutte le ciambelle riescono col buco'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'idioms_german',
      name: 'German Idioms & Slang',
      description: 'Understand and use fun German expressions',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['Ich verstehe nur Bahnhof', 'Daumen dr\u00fccken', 'Das ist nicht mein Bier'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'idioms_english',
      name: 'English Idioms & Slang',
      description: 'Sound like a native English speaker with idioms',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['Break the ice', 'Hit it off', 'On cloud nine'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'idioms_portuguese',
      name: 'Portuguese Idioms & Slang',
      description: 'Authentic Portuguese expressions and sayings',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['Estar com a pulga atr\u00e1s da orelha', 'Engolir sapos', 'P\u00e3o p\u00e3o, queijo queijo'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'idioms_brazilian',
      name: 'Brazilian Idioms & Slang',
      description: 'Talk like a true carioca with Brazilian slang',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.idioms,
      phraseCount: 40,
      coinPrice: 120,
      iconEmoji: '🎭',
      previewPhrases: ['Ficar de boa', 'Matar a pau', 'Dar um jeitinho'],
      tier: PackTier.standard,
    ),

    // ═══════════════════════════════════════════════════════════════
    // CONVERSATION STARTERS — 7 packs (35 phrases, 80 coins, standard)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'conversation_spanish',
      name: 'Spanish Icebreakers',
      description: 'Start great conversations with Spanish speakers',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['\u00bfDe d\u00f3nde eres?', '\u00bfQu\u00e9 te gusta hacer?', 'Mu\u00e9name tu sonrisa'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'conversation_french',
      name: 'French Icebreakers',
      description: 'Open doors to French conversation effortlessly',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['D\'o\u00f9 viens-tu?', 'Qu\'est-ce que tu aimes faire?', 'Raconte-moi quelque chose sur toi'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'conversation_italian',
      name: 'Italian Icebreakers',
      description: 'Break the ice with warm Italian openings',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['Di dove sei?', 'Cosa ti piace fare?', 'Raccontami di te'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'conversation_german',
      name: 'German Icebreakers',
      description: 'Kick off conversations in German with ease',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['Woher kommst du?', 'Was machst du gerne?', 'Erz\u00e4hl mir etwas \u00fcber dich'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'conversation_english',
      name: 'English Icebreakers',
      description: 'Smooth English openers to start any chat',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['Where are you from?', 'What do you do for fun?', 'Tell me something about yourself'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'conversation_portuguese',
      name: 'Portuguese Icebreakers',
      description: 'Start warm conversations in Portuguese',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['De onde \u00e9s?', 'O que gostas de fazer?', 'Conta-me algo sobre ti'],
      tier: PackTier.standard,
    ),
    const LanguagePack(
      id: 'conversation_brazilian',
      name: 'Brazilian Icebreakers',
      description: 'Friendly Brazilian openers to connect instantly',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.conversationStarters,
      phraseCount: 35,
      coinPrice: 80,
      iconEmoji: '💬',
      previewPhrases: ['De onde voc\u00ea \u00e9?', 'O que voc\u00ea gosta de fazer?', 'Me conta um pouco sobre voc\u00ea'],
      tier: PackTier.standard,
    ),

    // ═══════════════════════════════════════════════════════════════
    // VIDEO CALL — 4 packs (40 phrases, 150 coins, premium)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'videodate_spanish',
      name: 'Video Date Spanish',
      description: 'Impress your match on Spanish video calls',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.videoCall,
      phraseCount: 40,
      coinPrice: 150,
      iconEmoji: '📹',
      previewPhrases: ['\u00bfMe puedes ver bien?', 'Te ves incre\u00edble', 'Me encanta hablar contigo'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'videodate_french',
      name: 'Video Date French',
      description: 'Shine on French video dates with the right words',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.videoCall,
      phraseCount: 40,
      coinPrice: 150,
      iconEmoji: '📹',
      previewPhrases: ['Tu me vois bien?', 'Tu es magnifique', 'J\'adore parler avec toi'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'videodate_italian',
      name: 'Video Date Italian',
      description: 'Charm your Italian match over video',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.videoCall,
      phraseCount: 40,
      coinPrice: 150,
      iconEmoji: '📹',
      previewPhrases: ['Mi vedi bene?', 'Sei splendida', 'Adoro parlare con te'],
      tier: PackTier.premium,
    ),
    const LanguagePack(
      id: 'videodate_german',
      name: 'Video Date German',
      description: 'Nail your German video date with smooth phrases',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.videoCall,
      phraseCount: 40,
      coinPrice: 150,
      iconEmoji: '📹',
      previewPhrases: ['Kannst du mich gut sehen?', 'Du siehst toll aus', 'Ich liebe es, mit dir zu reden'],
      tier: PackTier.premium,
    ),

    // ═══════════════════════════════════════════════════════════════
    // COMPLETE BUNDLES — 7 packs (200 phrases, 500 coins, bundle)
    // ═══════════════════════════════════════════════════════════════
    const LanguagePack(
      id: 'bundle_spanish',
      name: 'Complete Spanish',
      description: 'Every Spanish pack in one massive bundle — best value',
      languageCode: 'es',
      languageName: 'Spanish',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇪🇸',
      previewPhrases: ['\u00a1Hola! \u00bfQu\u00e9 tal?', 'Me alegro de verte', '\u00bfVamos a tomar algo?'],
      tier: PackTier.bundle,
    ),
    const LanguagePack(
      id: 'bundle_french',
      name: 'Complete French',
      description: 'All French packs combined — the ultimate collection',
      languageCode: 'fr',
      languageName: 'French',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇫🇷',
      previewPhrases: ['Salut! Comment \u00e7a va?', 'Ravi de te voir', 'On prend un verre?'],
      tier: PackTier.bundle,
    ),
    const LanguagePack(
      id: 'bundle_italian',
      name: 'Complete Italian',
      description: 'Master Italian from ciao to perfetto — all in one',
      languageCode: 'it',
      languageName: 'Italian',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇮🇹',
      previewPhrases: ['Ciao! Come stai?', 'Che bello vederti', 'Andiamo a prendere qualcosa?'],
      tier: PackTier.bundle,
    ),
    const LanguagePack(
      id: 'bundle_german',
      name: 'Complete German',
      description: 'The full German experience — every phrase you need',
      languageCode: 'de',
      languageName: 'German',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇩🇪',
      previewPhrases: ['Hallo! Wie geht\'s?', 'Sch\u00f6n dich zu sehen', 'Gehen wir etwas trinken?'],
      tier: PackTier.bundle,
    ),
    const LanguagePack(
      id: 'bundle_english',
      name: 'Complete English',
      description: 'All English packs in one bundle — total fluency',
      languageCode: 'en',
      languageName: 'English',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇬🇧',
      previewPhrases: ['Hey! How are you?', 'Great to see you', 'Shall we grab a drink?'],
      tier: PackTier.bundle,
    ),
    const LanguagePack(
      id: 'bundle_portuguese',
      name: 'Complete Portuguese',
      description: 'All Portuguese packs combined — from Lisbon to Porto',
      languageCode: 'pt',
      languageName: 'Portuguese',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇵🇹',
      previewPhrases: ['Ol\u00e1! Como est\u00e1s?', 'Que bom ver-te', 'Vamos beber alguma coisa?'],
      tier: PackTier.bundle,
    ),
    const LanguagePack(
      id: 'bundle_brazilian',
      name: 'Complete Brazilian Portuguese',
      description: 'All Brazilian packs — from Rio to S\u00e3o Paulo and beyond',
      languageCode: 'pt-BR',
      languageName: 'Brazilian Portuguese',
      category: PhraseCategory.casual,
      phraseCount: 200,
      coinPrice: 500,
      iconEmoji: '🇧🇷',
      previewPhrases: ['Oi! Tudo bem?', 'Que bom te ver', 'Vamos tomar alguma coisa?'],
      tier: PackTier.bundle,
    ),
  ];
}

enum PackTier {
  standard,
  premium,
  bundle,
}

extension PackTierExtension on PackTier {
  String get displayName {
    switch (this) {
      case PackTier.standard:
        return 'Standard';
      case PackTier.premium:
        return 'Premium';
      case PackTier.bundle:
        return 'Bundle';
    }
  }

  String get badgeColor {
    switch (this) {
      case PackTier.standard:
        return '#4CAF50'; // Green
      case PackTier.premium:
        return '#FFD700'; // Gold
      case PackTier.bundle:
        return '#9C27B0'; // Purple
    }
  }
}
