import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';

import '../../../../core/error/exceptions.dart';
import '../models/video_profile_model.dart';

/// Remote datasource for video profile operations.
///
/// Handles Firebase Storage uploads and Firestore metadata for video profiles.
abstract class VideoProfileRemoteDataSource {
  /// Upload a video file and create a Firestore document.
  ///
  /// Returns a [VideoProfileModel] with the download URL and metadata.
  /// Emits upload progress via [onProgress] callback (0.0 to 1.0).
  Future<VideoProfileModel> uploadVideoProfile({
    required String userId,
    required String filePath,
    String? prompt,
    void Function(double progress)? onProgress,
  });

  /// Get the video profile for a specific user.
  Future<VideoProfileModel?> getVideoProfile(String userId);

  /// Delete the video profile for a specific user.
  Future<void> deleteVideoProfile(String userId);

  /// Get video profiles for discovery feed with pagination.
  Future<List<VideoProfileModel>> getVideoProfilesForDiscovery({
    int limit = 20,
    String? lastId,
  });

  /// Increment the view count for a video profile.
  Future<void> incrementViewCount(String videoProfileId);
}

class VideoProfileRemoteDataSourceImpl implements VideoProfileRemoteDataSource {
  final FirebaseFirestore _firestore;
  final FirebaseStorage _storage;

  static const String _collection = 'video_profiles';
  static const String _storagePath = 'video_profiles';
  static const int _maxDurationSeconds = 30;

  VideoProfileRemoteDataSourceImpl({
    FirebaseFirestore? firestore,
    FirebaseStorage? storage,
  })  : _firestore = firestore ?? FirebaseFirestore.instance,
        _storage = storage ?? FirebaseStorage.instance;

  @override
  Future<VideoProfileModel> uploadVideoProfile({
    required String userId,
    required String filePath,
    String? prompt,
    void Function(double progress)? onProgress,
  }) async {
    try {
      final file = File(filePath);
      if (!await file.exists()) {
        throw ServerException('Video file not found at path: $filePath');
      }

      // Validate file size (max 50MB for a 30s video)
      final fileSize = await file.length();
      if (fileSize > 50 * 1024 * 1024) {
        throw ValidationException(
            'Video file is too large. Maximum size is 50MB.');
      }

      // Upload video to Firebase Storage
      final storageRef =
          _storage.ref().child('$_storagePath/$userId/intro.mp4');

      final uploadTask = storageRef.putFile(
        file,
        SettableMetadata(
          contentType: 'video/mp4',
          customMetadata: {
            'userId': userId,
            if (prompt != null) 'prompt': prompt,
          },
        ),
      );

      // Track upload progress
      uploadTask.snapshotEvents.listen((snapshot) {
        final progress =
            snapshot.bytesTransferred / snapshot.totalBytes;
        onProgress?.call(progress);
      });

      // Await completion
      final snapshot = await uploadTask;
      final videoUrl = await snapshot.ref.getDownloadURL();

      // Generate thumbnail URL (using the same storage path convention)
      // In a production app, a Cloud Function would generate a real thumbnail.
      // For now, we store the video URL as fallback and can add thumbnail
      // generation later.
      String? thumbnailUrl;
      try {
        // Check if a thumbnail already exists (generated by Cloud Function)
        final thumbRef =
            _storage.ref().child('$_storagePath/$userId/thumbnail.jpg');
        thumbnailUrl = await thumbRef.getDownloadURL();
      } catch (_) {
        // No thumbnail available yet - this is fine
        thumbnailUrl = null;
      }

      // Delete any existing video profile document for this user
      final existingDocs = await _firestore
          .collection(_collection)
          .where('userId', isEqualTo: userId)
          .get();
      for (final doc in existingDocs.docs) {
        await doc.reference.delete();
      }

      // Create Firestore document
      final now = DateTime.now();
      final docRef = _firestore.collection(_collection).doc();

      final model = VideoProfileModel(
        id: docRef.id,
        userId: userId,
        videoUrl: videoUrl,
        thumbnailUrl: thumbnailUrl,
        durationSeconds: _maxDurationSeconds, // Will be validated client-side
        prompt: prompt,
        createdAt: now,
        updatedAt: now,
        viewCount: 0,
        isActive: true,
      );

      await docRef.set(model.toJson());

      debugPrint(
          '[VideoProfileDS] Uploaded video profile for user $userId');
      return model;
    } on FirebaseException catch (e) {
      debugPrint('[VideoProfileDS] Firebase error during upload: $e');
      throw ServerException('Failed to upload video: ${e.message}');
    } on ValidationException {
      rethrow;
    } catch (e) {
      debugPrint('[VideoProfileDS] Unexpected error during upload: $e');
      throw ServerException('Failed to upload video: $e');
    }
  }

  @override
  Future<VideoProfileModel?> getVideoProfile(String userId) async {
    try {
      final querySnapshot = await _firestore
          .collection(_collection)
          .where('userId', isEqualTo: userId)
          .where('isActive', isEqualTo: true)
          .limit(1)
          .get();

      if (querySnapshot.docs.isEmpty) {
        return null;
      }

      return VideoProfileModel.fromFirestore(querySnapshot.docs.first);
    } on FirebaseException catch (e) {
      debugPrint('[VideoProfileDS] Firebase error getting profile: $e');
      throw ServerException('Failed to get video profile: ${e.message}');
    } catch (e) {
      debugPrint('[VideoProfileDS] Error getting video profile: $e');
      throw ServerException('Failed to get video profile: $e');
    }
  }

  @override
  Future<void> deleteVideoProfile(String userId) async {
    try {
      // Delete from Firebase Storage
      try {
        final videoRef =
            _storage.ref().child('$_storagePath/$userId/intro.mp4');
        await videoRef.delete();
      } catch (e) {
        debugPrint(
            '[VideoProfileDS] Storage delete failed (may not exist): $e');
      }

      // Delete thumbnail if it exists
      try {
        final thumbRef =
            _storage.ref().child('$_storagePath/$userId/thumbnail.jpg');
        await thumbRef.delete();
      } catch (_) {
        // Thumbnail may not exist
      }

      // Delete Firestore document(s)
      final docs = await _firestore
          .collection(_collection)
          .where('userId', isEqualTo: userId)
          .get();

      for (final doc in docs.docs) {
        await doc.reference.delete();
      }

      debugPrint(
          '[VideoProfileDS] Deleted video profile for user $userId');
    } on FirebaseException catch (e) {
      debugPrint('[VideoProfileDS] Firebase error during delete: $e');
      throw ServerException('Failed to delete video profile: ${e.message}');
    } catch (e) {
      debugPrint('[VideoProfileDS] Error deleting video profile: $e');
      throw ServerException('Failed to delete video profile: $e');
    }
  }

  @override
  Future<List<VideoProfileModel>> getVideoProfilesForDiscovery({
    int limit = 20,
    String? lastId,
  }) async {
    try {
      Query query = _firestore
          .collection(_collection)
          .where('isActive', isEqualTo: true)
          .orderBy('createdAt', descending: true)
          .limit(limit);

      // Paginate using the last document ID
      if (lastId != null) {
        final lastDoc =
            await _firestore.collection(_collection).doc(lastId).get();
        if (lastDoc.exists) {
          query = query.startAfterDocument(lastDoc);
        }
      }

      final querySnapshot = await query.get();

      return querySnapshot.docs
          .map((doc) => VideoProfileModel.fromFirestore(doc))
          .toList();
    } on FirebaseException catch (e) {
      debugPrint('[VideoProfileDS] Firebase error loading discovery: $e');
      throw ServerException(
          'Failed to load discovery videos: ${e.message}');
    } catch (e) {
      debugPrint('[VideoProfileDS] Error loading discovery videos: $e');
      throw ServerException('Failed to load discovery videos: $e');
    }
  }

  @override
  Future<void> incrementViewCount(String videoProfileId) async {
    try {
      await _firestore.collection(_collection).doc(videoProfileId).update({
        'viewCount': FieldValue.increment(1),
      });
    } catch (e) {
      // Non-critical operation - log but don't throw
      debugPrint(
          '[VideoProfileDS] Failed to increment view count: $e');
    }
  }
}
