#!/usr/bin/env bash
# Writes PLACEHOLDER versions of the gitignored Firebase config files so that
# `flutter analyze` / `flutter test` can run in CI without any secret.
# The values are fake: nothing built from them can talk to the real project.
# Never overwrites an existing file (so running it locally is harmless).
set -euo pipefail
cd "$(dirname "$0")/../.."

if [ ! -f lib/firebase_options.dart ]; then
  cat > lib/firebase_options.dart <<'DART'
// CI PLACEHOLDER written by tools/security/ci_stub_firebase_config.sh.
// The real file is generated by the FlutterFire CLI and is gitignored.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('CI placeholder: unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ci-placeholder',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'demo-ci',
    storageBucket: 'demo-ci.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ci-placeholder',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'demo-ci',
    storageBucket: 'demo-ci.appspot.com',
    iosBundleId: 'com.example.ci',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'ci-placeholder',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'demo-ci',
    authDomain: 'demo-ci.firebaseapp.com',
    storageBucket: 'demo-ci.appspot.com',
  );
}
DART
  echo "wrote placeholder lib/firebase_options.dart"
fi

if [ ! -f android/app/google-services.json ]; then
  pkg="$(grep -oE 'applicationId\s*=?\s*"[^"]+"' android/app/build.gradle* 2>/dev/null | head -1 | grep -oE '"[^"]+"' | tr -d '"')"
  pkg="${pkg:-com.example.ci}"
  cat > android/app/google-services.json <<JSON
{
  "project_info": {"project_number": "000000000000", "project_id": "demo-ci", "storage_bucket": "demo-ci.appspot.com"},
  "client": [{
    "client_info": {"mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                    "android_client_info": {"package_name": "${pkg}"}},
    "oauth_client": [],
    "api_key": [{"current_key": "ci-placeholder"}],
    "services": {"appinvite_service": {"other_platform_oauth_client": []}}
  }],
  "configuration_version": "1"
}
JSON
  echo "wrote placeholder android/app/google-services.json (package ${pkg})"
fi
